#!/bin/bash

# look for a muttrc
muttrc=""
for file in *; do
  if [[ $file == "muttrc" ]]; then
    echo "found muttrc in $(pwd)"
    muttrc="$(pwd)/$file"
  fi
done

cd $HOME
for file in .*; do
  if [[ $file == ".muttrc" ]]; then
    echo "found .muttrc in $(pwd)"
    muttrc="$HOME/$file"
  fi
done

# bail otherwise
if [[ -z $muttrc ]]; then
  echo "could not file a muttrc file"
  exit 1
fi

read -ep "Enter IMAP mail server: " imap_server
read -ep "Enter SMTP mail server: " smtp_server
read -ep "Enter user: " user
read -ep "Enter password: " pass
read -ep "Enter mailbox prefix: " prefix

input=""
mboxes=""
while [[ "$input" != "done" ]]; do
  read -ep "Enter mailboxes (enter 'done' to finish): " input
  if [[ "$input" != "done" ]]; then
    mboxes="$mboxes \"$prefix$input\""
  fi
done

echo "backing up original muttrc"
mv "$muttrc" "$muttrc".bak

echo "# from setup_settings" >> "$muttrc"
echo "set my_server = \"$imap_server\"" >> "$muttrc"
echo "set my_smtp_server = \"$smtp_server\"" >> "$muttrc"
echo "set my_user = \"$user\"" >> "$muttrc"
echo "set my_pass = \"$pass\"" >> "$muttrc"
echo "mailboxes $mboxes" >> "$muttrc"
echo "$(cat "$muttrc".bak)" >> "$muttrc"
echo "" >> "$muttrc"
