#!/bin/bash
#
# took from vodik

dotfiles=$PWD
os=$(uname)

die() {
  echo >&2 "$1" && exit 1
}

link() {
  [[ -z $2 ]] && target=".${1##*/}" \
              || target="${2:-$target}"

  [[ -e "$target" && ! -h "$target" ]] && die "$0: $target exists in filesystem"
  [[ -d "$target"                   ]] && rm "$target"

  ln -fs "$dotfiles/$1" "$target"
  echo "linked $1 to $target"
}

# Deploy scriptlets {{{
dotfiles_git()        { link Common/git/gitconfig;       }

dotfiles_zsh() {
  link "$os"/zsh/zprofile
  link "$os"/zsh/zshrc
  link "$os"/zsh/zshenv

  link "$os"/zsh/dircolors
  link "$os"/zsh/inputrc

  [[ -d $HOME/.zsh ]] || mkdir $HOME/.zsh

  link "$os"/zsh/alias "$HOME/.zsh/alias.zsh"
  link "$os"/zsh/functions "$HOME/.zsh/functions.zsh"
}

dotfiles_vim() {
  link Common/vim
  link Common/vim/vimrc

  [[ ! -d "$HOME/.vim/swap" ]] && mkdir -p "$HOME/.vim/swap"

  if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim +PlugInstall
  fi

  [[ ! -d  "$HOME/.config/nvim" ]] && mkdir -p "$HOME/.config/nvim"
  link Common/neovim/init.vim "$HOME/.config/nvim"
}
# }}}

usage() {
  cat << HERE
Automated deploy function for dotfile syncronization.

SUPPORTED:
HERE

  for fn in $(compgen -A function dotfiles_); do
    echo "  ${fn#dotfiles_}"
  done
  exit ${1:-0}
}

deploy() {
  while (( $# )); do
    [[ $1 == "desktop" ]] && break

    cd && dotfiles_${1#dotfiles_}
    if [[ $? == 127 ]]; then
      echo  >&2 "Error: don't know how to deploy \"$1\""
      usage >&2 1
    fi
    shift
  done
}

if (( $# == 0 )); then
  read -r -p "Deploy all? " ans
  if [[ $ans =~ ^[Yy]$ ]]; then
    deploy $(compgen -A function dotfiles_)
  fi
elif [[ "$1" == "--help" ]]; then
  usage 0
else
  deploy $*
fi
