#!/bin/bash

set -e

cd arch
for dir in *; do
  if [[ "$dir" == "config" ]]; then
    for config in $dir/*; do
      echo "linking $config to $HOME/.$config"
      rm -rf "$HOME/.$config"
      ln -sf "$PWD/$config" "$HOME/.$config"
    done
  elif [[ "$dir" == "local" ]]; then
    mkdir -p $HOME/.local/share/systemd/user
    for unit in $dir/share/systemd/user/*; do
      echo "linking $unit to $HOME/.$unit"
      rm -rf "$HOME/.$unit"
      ln -sf "$PWD/$unit" "$HOME/.$unit"
    done
  elif [[ "$dir" == "bin" ]]; then
    echo "linking $dir to $HOME/$dir"
    ln -sfT "$PWD/$dir" "$HOME/$dir"
  else
    echo "linking $dir to $HOME/.$dir"
    ln -sfT "$PWD/$dir" "$HOME/.$dir"
  fi
done
