#! /bin/bash

bspc monitor -d I II III IV V VI VII VIII IX X

# Rules
bspc rule -a mpv floating=on
bspc rule -a scratchpad floating=on
bspc rule -a ncmpcpp floating=on
bspc rule -a gimp floating=on

# Visual options
bspc config top_padding 18

bspc config split_ratio           0.50
bspc config border_width          1
bspc config window_gap            4
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config auto_alternate        true
bspc config auto_cancel           true
bspc config normal_border_color   "#504339"
bspc config active_border_color   "#504339"
bspc config focused_border_color  "#817267"
bspc config presel_border_color   "#9a875f"
bspc config urgent_border_color   "#504339"
bspc config normal_frame_opacity  0.0
bspc config focused_frame_opacity 0.1

if [ -e "$BSPWM_TREE" ] ; then
  bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
  rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# Init
compton -bGc --config /home/hsp/.config/compton/config
feh --bg-scale /home/hsp/media/image/wallpaper/sun3.jpg &
xsetroot -cursor_name left_ptr &
wmname LG3D &
/home/hsp/.config/bspwm/panel &
