#! /bin/bash

bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Chromium -d ^2
bspc rule -a mpv --floating
bspc rule -a scratchpad --floating

bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -p 14 0 0 0
bspc monitor -a $REMAINING_DESKS

bspc config focused_border_color  #000000
bspc config normal_border_color   #CCCCFF

bspc config split_ratio           0.52
bspc config border_width          3
bspc config window_gap            6
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#$(pgrep panel) &> /dev/null
#[[ $? -eq 0 ]] && pkill panel
~/.config/bspwm/panel &
feh --bg-scale ~/wallpaper/bird.jpg &
compton -bGc --config ~/.config/compton/config &

# Restore
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
else
    bspc control --adopt-orphans
fi
