#! /bin/sh

FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"

bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -p 14 0 0 0
bspc monitor -a $REMAINING_DESKS

bspc rule -a Gimp       -d Eight --floating
bspc rule -a scratchpad          --floating

bspc config focused_border_color  #DDDDFF
bspc config normal_border_color   #000000

bspc config split_ratio           0.52
bspc config border_width          3
bspc config window_gap            6
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

~/.config/bspwm/panel &
feh --bg-scale ~/media/image/wallpaper/water.jpg &
compton -bGc --config ~/.config/compton/config &
