#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
  case $line in
    S*)
      # clock output
      sys_infos="${line#?}"
      ;;
    T*)
      # xtitle output
      title="${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            # focused occupied desktop
            wm_infos="$wm_infos %{U#FFbea492 F#FFFFFFFF}${name}%{U- F-}"
            ;;
          F*)
            # focused free desktop
            wm_infos="$wm_infos %{F#FFFFFFFF}${name}%{F-}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="$wm_infos %{F#FFFFFFFF}${name}%{F-}"
            ;;
          o*)
            # occupied desktop
            wm_infos="$wm_infos %{F#FFbea492}${name}%{F-}"
            ;;
          f*)
            # free desktop
            wm_infos="$wm_infos %{F#FF605655}${name}%{F-}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos %{F#FF8c644c}${name}%{F-}"
            ;;
          L*)
            # layout
            layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
            wm_infos="$wm_infos    %{F#FF857B52}$layout%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l F#FFbea492}$wm_infos%{F-} %{c F#FFbea492}$title%{F-} %{r F#FFbea492}$sys_infos%{F-}  "
done
