#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
  case $line in
    S*)
      # clock output
      sys_infos="${line#?}"
      ;;
    T*)
      # xtitle output
      title="${line#?}"
      ;;
    W*)
      # bspwm internal state
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          O*)
            # focused occupied desktop
            wm_infos="$wm_infos %{+u U#FFFFFFFF F#FFFFFFFF}${name}%{-u}"
            ;;
          F*)
            # focused free desktop
            wm_infos="$wm_infos %{F#FFFFFFFF}${name}"
            ;;
          U*)
            # focused urgent desktop
            wm_infos="$wm_infos %{F#FFFFFFFF}${name}"
            ;;
          o*)
            # occupied desktop
            wm_infos="$wm_infos %{F#FFbea492}${name}"
            ;;
          f*)
            # free desktop
            wm_infos="$wm_infos %{F#FF605655}${name}"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos %{F#FF8c644c}${name}"
            ;;
          L*)
            # layout
            layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
            if [[ $layout -eq "T" ]]; then
              wm_infos="$wm_infos    %{F#FF857B52}ø%"
            elif [[ $layout -eq "M" ]]; then
              wm_infos="$wm_infos    %{F#FF857B52}ÿ%"
            else
              wm_infos="$wm_infos    %{F#FF857B52}?%"
            fi
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l F#FFbea492}$wm_infos %{c F#FFbea492}$title %{rF#FFbea492 A:termite:}$sys_infos%{A}  "
done
