#!/bin/bash
#
# start_bspwm: useful things for bspwm to start

# bspwm panel vars
export PANEL_FIFO=/tmp/panel-fifo
export PANEL_HEIGHT=18

export BSPWM_TREE=/tmp/bspwm.tree
export BSPWM_HISTORY=/tmp/bspwm.history
export BSPWM_STACK=/tmp/bspwm.stack

# add bspwm dir to path
PATH="$PATH:/home/hsp/.config/bspwm"
export $PATH

# cursor theme doesn't get set properly without
xsetroot -cursor_name left_ptr &

# hotkeys
sxhkd &

# panels and start
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

while true ; do
    bspwm -s "$PANEL_FIFO" -p W || break
done
