[icons]
name = "awesome"

[theme]
name = "native"
[theme.overrides]
idle_bg = "#3b4252"
info_bg = "#3b4252"
idle_fg = "#d8dee9"
info_fg = "#d8dee9"
separator = "    "
separator_fg = "#d8dee9"
separator_bg = "#3b4252"
good_bg = "#3b4252"
warning_bg = "#3b4252"
critical_bg = "#3b4252"

[[block]]
block = "net"
format = "wired {ip} {speed_up;K} {speed_down;K}"
interval = 1

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} ({ip}) {speed_up;K} {speed_down;K}   {frequency}"
interval = 1

[[block]]
block = "temperature"
collapsed = false
format = "{max}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "memory"
display_type = "memory"
icons = true
clickable = false
interval = 1
warning_mem = 80
critical_mem = 95
format_mem = "{mem_used}/{mem_total} ({mem_used_percents})"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "backlight"
device = "intel_backlight"
invert_icons = true

[[block]]
block = "sound"
step_width = 3

#[[block]]
#block = "ibus"
#[block.mappings]
#"hangul" = "KO"
#"xkb:us:dvorak:eng" = "EN(DV)"
#"xkb:us::eng" = "EN"

[[block]]
block = "time"
format = "%F %I:%M%p"
timezone = "US/Pacific"
interval = 60
