[icons]
icons = "awesome"

[theme]
theme = "native"
[theme.overrides]
idle_bg = "#3b4252"
info_bg = "#3b4252"
idle_fg = "#d8dee9"
info_fg = "#d8dee9"
separator = "    "
separator_fg = "#d8dee9"
separator_bg = "#3b4252"
good_bg = "#3b4252"
warning_bg = "#3b4252"
critical_bg = "#3b4252"

[[block]]
block = "bluetooth"
mac = "34:31:8F:45:F2:78"
hide_disconnected = true

[[block]]
block = "net"
interval = 1
format = "$speed_down.eng(3,B,K)$speed_up.eng(3,B,K) {$signal_strength $ssid $frequency|Wired} ($device)"

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "cpu"
interval = 1
format = "$barchart.str() $utilization.eng()"

[[block]]
block = "memory"
format_mem = "$mem_total_used_percents.eng(2)"

[[block]]
block = "battery"
format = "$percentage| $time"

[[block]]
block = "backlight"
device = "intel_backlight"
invert_icons = true

[[block]]
block = "sound"
step_width = 3

#[[block]]
#block = "ibus"
#[block.mappings]
#"hangul" = "KO"
#"xkb:us:dvorak:eng" = "EN(DV)"
#"xkb:us::eng" = "EN"

[[block]]
block = "time"
format = "%F %I:%M%p"
timezone = "US/Pacific"
interval = 60
