[icons]
name = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#3b4252"
info_bg = "#3b4252"
idle_fg = "#d8dee9"
info_fg = "#d8dee9"
separator = "    "
separator_fg = "#d8dee9"
separator_bg = "#3b4252"
good_bg = "#3b4252"
warning_bg = "#3b4252"
critical_bg = "#3b4252"

[[block]]
block = "net"
device = "wlan0"
ssid = true
interval = 1

[[block]]
block = "temperature"
collapsed = false
format = "{max}°"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}%"

[[block]]
block = "memory"
format_mem = "{Mup}%"
display_type = "memory"
icons = true
clickable = false
interval = 1
warning_mem = 80
critical_mem = 95

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 3

#[[block]]
#block = "ibus"
#[block.mappings]
#"hangul" = "KO"
#"xkb:us:dvorak:eng" = "EN(DV)"
#"xkb:us::eng" = "EN"

[[block]]
block = "time"
format = "%F %I:%M%p"
timezone = "US/Pacific"
interval = 60
