[icons]
name = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#262626"
info_bg = "#262626"
idle_fg = "#cccccc"
info_fg = "#cccccc"
separator_fg = "#dddddd"
separator_bg = "#262626"
good_bg = "#262626"
warning_bg = "#262626"
critical_bg = "#262626"

[[block]]
block = "net"
device = "wlan0"
ssid = true
interval = 5

[[block]]
block = "cpu"
interval = 1
format = "{utilization}%"

[[block]]
block = "memory"
format_mem = "{Mup}%"
display_type = "memory"
icons = true
clickable = false
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[icons.overrides]
backlight_empty = "B: "
backlight_partial1 = "B: "
backlight_partial2 = "B: "
backlight_partial3 = "B: "
backlight_full = "B: "
[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "time"
format = "%F %I:%M%p"
timezone = "US/Pacific"
interval = 60
