general {
        output_format = i3bar
        colors = true
        interval = 10
}

#order += "ipv6"
order += "disk /"
#order += "run_watch DHCP"
#order += "run_watch VPN"
order += "wireless wlan0"
order += "ethernet eth0"
order += "battery 0"
order += "load"
order += "cpu_temperature 0"
order += "volume master"
order += "time"

wireless wlan0 {
        format_up = "W: (%quality at %essid, %bitrate) %ip "
        format_down = "W: down "
}

ethernet eth0 {
        # if you use %speed, i3status requires the cap_net_admin capability
        format_up = "E: %ip (%speed) "
        format_down = "E: down " 
}

battery 0 {
        #format = "%status %percentage %remaining %emptytime"
        format = "%status %percentage "
        path = "/sys/class/power_supply/BAT%d/uevent"
        threshold_type = percent
        low_threshold = 15
}

run_watch DHCP {
        pidfile = "/var/run/dhclient*.pid "
}

run_watch VPN {
        pidfile = "/var/run/vpnc/pid "
}

time {
        format = "%Y-%m-%d %H:%M "
}

load {
        format = "load %5min %15min"
}

cpu_temperature 0 {
        format = "T: %degrees °C "
        path = "/sys/devices/platform/coretemp.0/temp1_input"
}

disk "/" {
        format = "%used / %total used "
}

volume master {
        format = "♪: %volume " 
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}
