[[ -o interactive ]] || return 0

# Turn autocomplete on
autoload -Uz compinit edit-command-line vcs_info zmv
_zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
mkdir -p "${_zcompdump:h}"
if [[ ! -f $_zcompdump || -n ${_zcompdump}(#qN.mh+24) ]]; then
  compinit -d "$_zcompdump"
else
  compinit -C -d "$_zcompdump"
fi
unset _zcompdump

KEYTIMEOUT=1

# history
mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history"
if [[ ! -f $HISTFILE && -f ~/.zhistory ]]; then
  mv -n ~/.zhistory "$HISTFILE"
fi
HISTSIZE=50000
SAVEHIST=50000

# changing directories
setopt autocd autopushd chaselinks pushdignoredups pushdtohome

# completion
setopt alwaystoend automenu completealiases completeinword nolistbeep \
       listpacked listtypes

# expansion and globbing
setopt badpattern braceccl extendedglob dotglob numericglobsort

# history
setopt histignorealldups histignorespace \
       histreduceblanks histsavenodups histverify appendhistory \
       share_history

# io
setopt correct noflowcontrol interactivecomments printexitvalue

# jobs
setopt nobgnice notify

# prompt
setopt promptsubst

# zle
setopt nobeep vi

bindkey -v
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
zle -A .backward-kill-word vi-backward-kill-word
zle -A .backward-delete-char vi-backward-delete-char

# completion style {{{
# menu completion
zstyle ':completion:*' menu select

# autoload new files in $PATH
zstyle ':completion:*' rehash true

# Homebrew coreutils prefixes GNU dircolors with g on macOS.
if [[ -f ~/.dircolors ]]; then
  if (( $+commands[gdircolors] )); then
    eval "$(gdircolors -b "$HOME/.dircolors")"
  elif (( $+commands[dircolors] )); then
    eval "$(dircolors -b "$HOME/.dircolors")"
  fi
fi

# colors for file completion
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# complete all processes
zstyle ':completion:*:processes' command 'ps -e'
zstyle ':completion:*:processes-names' command 'ps -eo comm'

# cache completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

# don't complete working directory in parent
zstyle ':completion:*' ignore-parents parent pwd
# }}}

# title (for vte, xterm and rxvt) {{{
case "$TERM" in
    vte*|xterm*|rxvt*|alacritty|ghostty|screen*|tmux*|foot)
        update_title() { print -Pn '\e];%n (%~) - Terminal\a' } ;;
    *)
        update_title() {} ;;
esac
# }}}

# prompt {{{
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr '%F{red}s%F{white}'
zstyle ':vcs_info:*' unstagedstr '%F{red}u%F{white}'
zstyle ':vcs_info:git*' formats "%F{green}%s %b%F{white} %m%u%c% "

zle -N zle-line-init
zle -N zle-keymap-select

vimode=i
# set vimode to current editing mode
function zle-line-init zle-keymap-select {
    vimode="${${KEYMAP/vicmd/c}/(main|viins)/i}"
    zle reset-prompt
}

# PROMPT='(%F{blue}$vimode%b%f) %b%F{grey}%n%F{cyan}@%F{red}%m%F{grey} gcp:%F{red}$(gcloud_project)%b%f $ '
PROMPT='(%F{blue}$vimode%b%f) %b%F{grey}%n%F{cyan}@%F{red}%m%F{grey} $ '
RPROMPT='${vcs_info_msg_0_} %F{red}%~'
# }}}

precmd() {
  vcs_info
  update_title
}

# Environmental
export EDITOR=nvim
export PAGER=less

# External Config
for snippets ($HOME/.zsh/*.zsh(N))
  source $snippets

[[ -f ~/code/z/z.sh ]] && source ~/code/z/z.sh

alias -s txt=$EDITOR
alias -s PKGBUILD=$EDITOR

export TIMEFMT=$'real\t%E\nuser\t%U\nsys\t%S'
export FZF_DEFAULT_COMMAND='rg --hidden --files --color=never'

# Optional tools must not make a fresh shell fail to start.
[[ ! -s $BUN_INSTALL/_bun ]] || source "$BUN_INSTALL/_bun"
