[[ $- != *i* ]] && return ]]

fpath=($HOME/.zsh/completion $fpath )

# Turn autocomplete on
autoload -U colors && colors 
autoload -U compinit && compinit
autoload -Uz vcs_info

# smart urls
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# history
HISTFILE=~/.zhistory
HISTSIZE=1500
SAVEHIST=1000

setopt APPEND_HISTORY			# Same history for all sessions
setopt HIST_IGNORE_ALL_DUPS		# No dupes in history
setopt HIST_REDUCE_BLANKS

# changing directories
setopt auto_cd
setopt auto_pushd
setopt cdable_vars
setopt chase_links
setopt pushd_ignore_dups
setopt pushd_silent
setopt pushd_to_home

# completion
setopt always_to_end
setopt auto_menu
setopt auto_name_dirs
setopt auto_param_keys
setopt auto_param_slash
setopt auto_remove_slash
setopt complete_aliases
setopt complete_in_word
setopt list_ambiguous
setopt list_packed
unsetopt menu_complete

# expansion and globbing
setopt brace_ccl
setopt extended_glob
setopt long_list_jobs
setopt multios
setopt prompt_subst

# input/output
setopt correct
setopt interactive_comments
setopt rc_quotes
setopt short_loops
unsetopt clobber
unsetopt flowcontrol

# Enable vi mode
bindkey -v

# Enable setting terminal titles
case $TERM in
  xterm*|rxvt*|screen*|gnome*)
     precmd() { 
       print -Pn "\e]0;%m:%~\a" 
       vcs_info 
     }
     preexec () { print -Pn "\e]0;$1\a" }
    ;;
esac


# completion style
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path /tmp
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' ignore-parents parent pwd
                                
# Enable git in prompt
zstyle ':vcs_info:*' enable git   
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git*' formats "%F{blue}%s%F{white}:%F{green}%b%F{white} %m%u%c% "
zstyle ':vcs_info:*' stagedstr '%F{red}S%F{white}'
zstyle ':vcs_info:*' unstagedstr '%F{red}U%F{white}'

PROMPT='%B┌ %F{blue}%n%b@%B%F{blue}%m%b %B[%~] ${vcs_info_msg_0_}
└╼ $%b%f '

# Environmental
[[ -n "$TMUX" ]] && export TERM=screen-256color
export EDITOR=vim

# External Config
if [[ -r ~/.dircolors ]] && type -p dircolors >/dev/null; then
    eval $(dircolors -b "$HOME/.dircolors")
fi

for snippets ($HOME/.zsh/*.zsh(N))
  source $snippets

source /usr/share/zsh/plugins/zsh-syntax-highlight/zsh-syntax-highlighting.zsh

# Allow backspace past insert position in vi-mode
zle -A .backward-kill-word vi-backward-kill-word
zle -A .backward-delete-char vi-backward-delete-char
