[[ -o interactive ]] || return

# Turn autocomplete on
autoload -Uz compinit edit-command-line vcs_info zmv

# completion dump under XDG; rebuild at most once per day
_zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
mkdir -p "${_zcompdump:h}"
if [[ -n ${_zcompdump}(#qN.mh+24) ]]; then
  compinit -d "$_zcompdump"
else
  compinit -C -d "$_zcompdump"
fi
unset _zcompdump

KEYTIMEOUT=1

# history
mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history"
if [[ ! -f $HISTFILE && -f ~/.zhistory ]]; then
  mv -n ~/.zhistory "$HISTFILE"
fi
HISTSIZE=50000
SAVEHIST=50000

# changing directories
setopt autocd autopushd chaselinks pushdignoredups pushdtohome

# completion
setopt alwaystoend automenu completealiases completeinword nolistbeep \
       listpacked listtypes

# expansion and globbing
setopt badpattern braceccl extendedglob dotglob numericglobsort

# history
setopt histignorealldups histignorespace \
       histreduceblanks histsavenodups histverify appendhistory \
       inc_append_history share_history

# io
setopt correct noflowcontrol interactivecomments printexitvalue

# jobs
setopt nobgnice notify

# prompt
setopt promptsubst

# zle
setopt nobeep vi

bindkey -v
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
zle -A .backward-kill-word vi-backward-kill-word
zle -A .backward-delete-char vi-backward-delete-char

# completion style {{{
# menu completion
zstyle ':completion:*' menu select

# colors for file completion
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# complete all processes
zstyle ':completion:*:processes' command 'ps -e'
zstyle ':completion:*:processes-names' command 'ps -eo comm'

# cache completion
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

# don't complete working directory in parent
zstyle ':completion:*' ignore-parents parent pwd
# }}}

# title (for vte, xterm and rxvt) {{{
case "$TERM" in
    vte*|xterm*|rxvt*|alacritty|ghostty|xterm-ghostty)
        update_title() { print -Pn '\e];%n (%~) - Terminal\a' } ;;
    *)
        update_title() {} ;;
esac
# }}}

# prompt {{{
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes false
zstyle ':vcs_info:*' stagedstr '%F{red}s%F{white}'
zstyle ':vcs_info:*' unstagedstr '%F{red}u%F{white}'
zstyle ':vcs_info:git*' formats "%F{green}%s %b%F{white} %m%u%c% "

zle -N zle-line-init
zle -N zle-keymap-select

vimode=i
# set vimode to current editing mode
function zle-line-init zle-keymap-select {
    vimode="${${KEYMAP/vicmd/c}/(main|viins)/i}"
    zle reset-prompt
}

PROMPT='(%F{blue}$vimode%b%f) %b%F{grey}%n%F{cyan}@%F{red}%m%F{grey} $ '
RPROMPT='${vcs_info_msg_0_} %F{red}%~'

export EDITOR=nvim
export PAGER=less

precmd() {
  vcs_info
  update_title
}

# External Config
for snippets ($HOME/.zsh/*.zsh(N))
  source $snippets

[[ -f ~/code/z/z.sh ]] && source ~/code/z/z.sh

alias -s txt=$EDITOR
alias -s PKGBUILD=$EDITOR

export TIMEFMT=$'real\t%E\nuser\t%U\nsys\t%S'
