# Set terminal options
xrdb -merge ~/.Xresources &

# Wait 15 seconds for connection
# delay_dropbox &

# Ibus for Korean input
# ibus-daemon -drx

# Disable touchpad when typing
syndaemon -K -d -i 1

# Key bindings
xbindkeys &

# Music
mpd

# Custom keyboard layout
/home/hsp/bin/delay_xmodmap &

# Fix dual monitor settings
/home/hsp/bin/mymonitor &

# Run window manager
exec i3
