# Set terminal options
xrdb -merge ~/.Xresources &

# Wait 15 seconds for connection
# delay_dropbox & 

# Ibus for Korean input
# ibus-daemon -drx

# Disable touchpad when typing
syndaemon -K -d -i 1

# Key bindings
xbindkeys &

# Music
mpd

# Custom keyboard layout
delay_xmodmap &

# Mounting aid
udiskie &

# Fix dual monitor settings
mymonitor &

# Run window manager
exec i3
