# Set terminal options
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources &

xset +fp /usr/share/fonts/local
xset fp rehash

# ???
pulseaudio --start &

# nvidia performance boost?
nvidia-settings -a GlyphCache=1
nvidia-settings -a InitialPixmapPlacement=2

exec i3
