# Check for interactive
[[ $- = *i* ]] || return ]]

# set path
PERSONAL_PATH="/home/hsp/bin"
GEM_PATH="/home/hsp/.gem/ruby/1.9.1/bin"
MATLAB_PATH="/usr/local/MATLAB/R2011a/bin"
ECLIPSE_PATH="/opt/java/bin"

export PATH=$PERSONAL_PATH:$GEM_PATH:$MATLAB_PATH:$ECLIPSE_PATH:$PATH
unset PERSONAL_PATH
unset GEM_PATH
unset MATLAB_PATH

# less is moar
export LESS=-R # use -X to avoid sending terminal initialization
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'

# history
export HISTIGNORE="&:ls:[bf]g:exit:reset:clear:cd *"
export HISTCONTROL="ignoreboth:erasedups"
export HISTSIZE=1000
export HISTFILESIZE=2000

# settings
shopt -s cdspell dirspell extglob histverify no_empty_cmd_completion checkwinsize
set -o notify           # notify of completed background jobs immediately
ulimit -S -c 0          # disable core dumps

# --- External configs ---
source_bash_completion() {
  local f
  [[ $BASH_COMPLETION ]] && return 0
  for f in /{etc,usr/share/bash-completion}/bash_completion; do
    if [[ -r $f ]]; then
      . "$f"
      return 0;
    fi
  done
}

source_bash_completion
unset -f source_bash_completion

for config in $HOME/.bash/*; do
  [[ -r $config ]] && . $config
done

[[ -f /usr/share/git/git-prompt.sh ]] && . /usr/share/git/git-prompt.sh

if [[ -r ~/.dircolors ]] && type -p dircolors >/dev/null; then
  eval $(dircolors -b "$HOME/.dircolors")
fi

export EDITOR=vim
export BROWSER=chromium
