# Ibus vars (old)
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# color for less
export LESS=-R # use -X to avoid sending terminal initialization
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'
export PAGER=less

# no wine msgs
export WINEDEBUG=-all

# disable less history file
export LESSHISTFILE=-

# add things to path
PATH="$PATH:/home/hsp/bin:/home/hsp/.gem/ruby/2.0.0/bin"
PATH="$PATH:/usr/local/MATLAB/MATLAB_Production_Server/R2013a/bin"
export PATH

# colors
if [[ -f ~/.dircolors ]] && type -p dircolors >/dev/null; then
    eval $(dircolors -b ~/.dircolors)
fi

if (( UID )); then
    [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx &> ~/.xlog
fi
