# Ibus vars
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# ccache
export CCACHE_DIR=/tmp/ccache

# color for less
export LESS=-R # use -X to avoid sending terminal initialization
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'
export PAGER=less

# disable less history file
export LESSHISTFILE=-

# golang
GOPATH="$HOME/code/gocode"
export GOPATH

# add things to path
PATH="$PATH:$HOME/bin:$GOPATH/bin"
export PATH

# colors
if [[ -f ~/.dircolors ]] && type -p dircolors >/dev/null; then
  eval $(dircolors -b ~/.dircolors)
fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#if [ -n "$DESKTOP_SESSION" ];then
#  eval $(gnome-keyring-daemon --start --components=ssh)
#  export SSH_AUTH_SOCK
#fi
#
export HOMEBREW_GITHUB_API_TOKEN=a4f0d5dca8c24ae024051dd6ef845f6b900c9c3b
