# color for less
export LESS=-R # use -X to avoid sending terminal initialization
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'
export PAGER=less

# disable less history file
export LESSHISTFILE=-

# golang
GOPATH="$HOME/code/gocode"
export GOPATH

# add things to path
PATH="$PATH:$HOME/bin:$GOPATH/bin"
export PATH

# colors
if [[ -f ~/.dircolors ]] && type -p dircolors >/dev/null; then
  eval $(dircolors -b ~/.dircolors)
fi

# let's not expose private keys...
# old key is gone :p
homebrew=$(cat secret/homebrew)

export HOMEBREW_GITHUB_API_TOKEN=$homebrew
