# color for less
export LESS=-R # use -X to avoid sending terminal initialization
export LESS_TERMCAP_mb=$'\e[01;34m'
export LESS_TERMCAP_md=$'\e[01;34m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'
export PAGER=less

# disable less history file
export LESSHISTFILE=-

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# add things to path
export PATH="/usr/local/sbin:$HOME/bin:$HOME/code/zig/build/bin:$HOME/go/bin:$PATH"

# colors
if [[ -f ~/.dircolors ]] && type -p dircolors >/dev/null; then
  eval $(dircolors -b ~/.dircolors)
fi

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
